# Generated by Django 3.0.6 on 2020-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200527_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('-votes',), 'verbose_name': 'Escolha', 'verbose_name_plural': 'Escolhas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
